name: Production Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run full test suite
        run: npm run test:ci
      
      - name: Production build
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Check for console.logs (optional)
        run: |
          if grep -r "console\\.log" src/ --exclude-dir=__tests__; then
            echo "⚠️ Warning: console.log statements found in source code"
          fi

