name: Staging Validation

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Safety timeout: typical run ~3-5min, max 10min to allow full completion
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm run test:ci
      
      - name: Build check
        run: npm run build

